services:
    restlessrancor.attachmentshields.listener:
        class: restlessrancor\attachmentshields\event\main_listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }